# Generated by Django 5.1.4 on 2024-12-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_privatechat_user_1_remove_privatemessage_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.account'),
        ),
    ]
