# Generated by Django 5.1.4 on 2024-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_account_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.SlugField(default='asdasdasd'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=6, verbose_name='Пол'),
        ),
    ]
