# Generated by Django 5.1.4 on 2024-12-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_account_username_alter_account_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.SlugField(),
        ),
    ]
