# Generated by Django 5.1.4 on 2024-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_photo',
            field=models.ImageField(default='photo/chat/default/Аватарка чата по умолчанию.jpg', upload_to='photo/chat/%Y/%m/%d', verbose_name='Фото чата'),
        ),
    ]
