# Generated by Django 5.1.4 on 2024-12-24 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_account_user_alter_chat_admin_privatechat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='API.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagefromuser', to='API.account'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='second_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privatechatseconduser', to='API.account'),
        ),
    ]
