# Generated by Django 5.1.4 on 2024-12-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_message_send_time_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-send_time'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
