# Generated by Django 5.1.4 on 2025-01-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_time'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='online',
        ),
    ]
