# Generated by Django 5.1.4 on 2025-01-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_chat_options_chat_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_photo',
            field=models.ImageField(default='photo/chat/default/Аватарка чата по умолчанию.jpg', null=True, upload_to='photo/chat/%Y/%m/%d', verbose_name='Фото чата'),
        ),
    ]
