# Generated by Django 5.1.4 on 2025-01-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_chat_chat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagefromuser', to='API.account'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='API.account'),
        ),
    ]
