# Generated by Django 5.1.5 on 2025-01-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_message_user_alter_participants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_private',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatseconduser', to='API.privatechat', verbose_name='Приватный чат'),
        ),
    ]
